### ISSUE TITLE
Add links to genes in the phylogenic tree

### ISSUE THREAD

**Issue by mboudet** [genenotebook/react-bio-viz#297]
Hello,

I'd like to add links to existing genes in the phylogenic tree view.
 As far as I know, on the GNB side, we have a list of existing genes associated with a specific tree, so it should be fairly simple: 

* When reaching an end node, check if the name is in the set of genes
* If yes, replace the name in the graph by an link pointing to the gene (or an onclick -> Redirect...)

It would be done by passing two optional props to the tree : a set of genes, and a base url to build the url.

**Comment by mboudet** [comment]
Might be better to pass a Dict with the gene_id as key and the url as value, and manage the url construction on the GNB side

**Comment by mboudet** [comment]
Another issue is that we store the gene_id, but in the tree it might have a prefix, so it will not match directly

**Comment by holmrenser** [comment]
My idea for this would be that the Tree component takes an optional LeafNode component argument, so that any customization (like having linkouts) can be implemented on the user side.

**Comment by mboudet** [comment]
Agreed, a custom callable would be more flexible. (and would avoid having to update this lib every time we need to add something in GNB)

I also agree on the 'user need to validate the data'. (Plus it's acceptable to just render the name if the gene is not in the DB I think)

**Comment by holmrenser** [comment]
Indeed, one of the reasons I moved this out of the genenotebook code base is that I use it in other projects as well.

**Comment by holmrenser** [comment]
Implemented in https://github.com/genenotebook/react-bio-viz/commit/f720386c46cf6fe0d6bcf4998f41a45046ed9bdd

**Comment by mboudet** [comment]
Alright, closing the issue here since it's now a GNB-side issue
